config/routes.rb
Rails.application.routes.draw do
  
  devise_for :funcionarios, :controllers => {registrations: 'registrations'}
  get 'controll_funcionarios/index'
  resources :doados
  resources :doadores
  resources :welcome
  resources :controll_funcionarios
  root to:  "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doado.rb
class Doado < ApplicationRecord
    belongs_to :doador

     validates :Litros , numericality: true
end

app/models/doador.rb
class Doador < ApplicationRecord
	has_many :doados 
	validates :Nome , :CPF , :Tipo_Sanguineo, :Fator_RH, presence: true
	validates :CPF , numericality: true , uniqueness: true , length: { is: 11 }
	


end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	

end

app/controllers/controll_funcionarios_controller.rb
class ControllFuncionariosController < ApplicationController
   before_action :authenticate_funcionario!
   def index
  	@funcionarios=Funcionario.all
   end

end

app/controllers/doadores_controller.rb
class DoadoresController < ApplicationController
  before_action :authenticate_funcionario!
  before_action :set_doador, only: [:show, :edit, :update, :destroy]

  # GET /doadores
  # GET /doadores.json
  def index
    @doadores = Doador.all
  end

  # GET /doadores/1
  # GET /doadores/1.json
  def show
  end

  # GET /doadores/new
  def new
    @doador = Doador.new
  end

  # GET /doadores/1/edit
  def edit
  end

  # POST /doadores
  # POST /doadores.json
  def create
    @doador = Doador.new(doador_params)

    respond_to do |format|
      if @doador.save
        format.html { redirect_to @doador, notice: 'Doador foi cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @doador }
      else
        format.html { render :new }
        format.json { render json: @doador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doadores/1
  # PATCH/PUT /doadores/1.json
  def update
    respond_to do |format|
      if @doador.update(doador_params)
        format.html { redirect_to @doador, notice: 'Doador foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @doador }
      else
        format.html { render :edit }
        format.json { render json: @doador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doadores/1
  # DELETE /doadores/1.json
  def destroy
    @doador.doados.each do |doado|
      doado.destroy
      end
    @doador.destroy
    respond_to do |format|
      format.html { redirect_to doadores_url, notice: 'Doador foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doador
      @doador = Doador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doador_params
      params.require(:doador).permit(:Nome, :CPF, :Tipo_Sanguineo, :Fator_RH)
    end
end

app/controllers/doados_controller.rb
class DoadosController < ApplicationController
  before_action :authenticate_funcionario!
  before_action :set_doado, only: [:show, :edit, :update, :destroy]

  # GET /doados
  # GET /doados.json
  def index
    @doados = Doado.all
  end

  # GET /doados/1
  # GET /doados/1.json
  def show
  end

  # GET /doados/new
  def new
    @doado = Doado.new
  end

  # GET /doados/1/edit
  def edit
  end

  # POST /doados
  # POST /doados.json
  def create
    @doado = Doado.new(doado_params)

    respond_to do |format|
      if @doado.save
        format.html { redirect_to @doado, notice: 'Doação foi adicionada com sucesso.' }
        format.json { render :show, status: :created, location: @doado }
      else
        format.html { render :new }
        format.json { render json: @doado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doados/1
  # PATCH/PUT /doados/1.json
  def update
    respond_to do |format|
      if @doado.update(doado_params)
        format.html { redirect_to @doado, notice: 'Doação foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @doado }
      else
        format.html { render :edit }
        format.json { render json: @doado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doados/1
  # DELETE /doados/1.json
  def destroy
    @doado.destroy
    respond_to do |format|
      format.html { redirect_to doados_url, notice: 'Doação foi apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doado
      @doado = Doado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doado_params
      params.require(:doado).permit(:Data, :Litros, :Local, :doador_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:funcionario).permit(:gerente, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:funcionario).permit(:gerente, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		render "index"
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controll_funcionarios_helper.rb
module ControllFuncionariosHelper
end

app/helpers/doadores_helper.rb
module DoadoresHelper
end

app/helpers/doados_helper.rb
module DoadosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/controll_funcionarios/index.html.erb
<h1>Listagem de funcionarios</h1>

<%if current_funcionario.gerente==true%>
<%=image_tag("logos/lista.png",size: "100x130", alt: "Edit Entry")%>
<table>
  <thead>
    <tr>

      <th>Email</th>
      
      <th>Cargo</th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.email %></td>

        <%if funcionario.gerente==true%>
           <td><%= "Gerente" %></td>
        <%else%>
          <td><%= "Funcionario" %></td>
        <%end%>

        
      </tr>
    <% end %>
  </tbody>
</table>
<%else%>
<p>Apenas visivel para Gerentes</p>
<%end%>
<br><br><br>
<%= link_to 'Pagina inicial', root_path %> 

app/views/doadores/_form.html.erb
<%= form_with(model: doador, local: true) do |form| %>
  <% if doador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doador.errors.count, "error") %> prohibited this doador from being saved:</h2>

      <ul>
      <% doador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :Nome %>
  </div>

  <div class="field">
    <%= form.label :CPF %>
    <%= form.text_field :CPF %>
  </div>

  <div class="field">
    <%= form.label :Tipo_Sanguineo %>
    <%= select("doador","Tipo_Sanguineo",['AB',' A',' B',' 0'],{include_blank: true})%>
  </div>

  <div class="field">
    <%= form.label :Fator_RH %>
    <%= select("doador","Fator_RH",['Negativo','Positivo'],{include_blank: true})%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doadores/edit.html.erb
<h1>Editando dador</h1>

<%= render 'form', doador: @doador %>


<%= link_to 'Voltar', doadores_path %>

app/views/doadores/index.html.erb
<h1>Doadores</h1> 
<p id="notice"><%= notice %></p>

<%=image_tag("logos/lista.png",size: "100x130", alt: "Edit Entry")%>
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Fator rh</th>
      <th>Tipo sanguineo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doadores.each do |doador| %>
      <tr>
        <td><%= doador.Nome %></td>
        <td><%= doador.CPF %></td>
        <td><%= doador.Fator_RH %></td>
        <td>  Tipo:<%=  doador.Tipo_Sanguineo %></td>  
         
        <td><%= link_to 'Histórico', doador %></td>
        <%if current_funcionario.gerente==true%>
        <td><%= link_to 'Editar dados', edit_doador_path(doador) %></td>
        
        <td><%= link_to 'Apagar registro', doador, method: :delete, data: { confirm: 'Tem certeza que deseja apagar este doador e seu historico?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Adicionar doador', new_doador_path %>|
<%= link_to 'Pagina inicial', root_path %> 

app/views/doadores/new.html.erb
<h1>Novo doador</h1><%=image_tag("logos/registros.png",size: "100x130", alt: "Edit Entry")%>

<%= render 'form', doador: @doador %>

<%= link_to 'Voltar', doadores_path %>

app/views/doadores/show.html.erb
<p id="notice"><%= notice %></p>
<%=image_tag("logos/usuario.png",size: "90x100", alt: "Edit Entry")%>
<p>
  <strong>Nome:</strong>
  <%= @doador.Nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @doador.CPF %>
</p>

<p>
  <strong>Tipo sanguineo:</strong>
  <%= @doador.Tipo_Sanguineo %>
</p>

<p>
  <strong>Fator rh:</strong>
  <%= @doador.Fator_RH %>
</p>

<hr>
<%if current_funcionario.gerente==true%>
<%=image_tag("logos/historico.png",size: "140x130", alt: "Edit Entry")%>
<ul>
     <% @doador.doados.each do |doado| %>
    <li><p>
    	<%= "Data:#{doado.Data}"  %><br />
    	<%= "ml:#{doado.Litros}" %><br />
    	<%= "Local:#{doado.Local}" %><br />
    	</p>
    	<% end %>
      <%else%>
      <p>
        Historico diponivel apenas para gerentes
      </p>
      <%end%>

</ul>
















<%if current_funcionario.gerente==true%>
<%= link_to 'Editar dados', edit_doador_path(@doador) %> 
|<%end%>
<%= link_to 'Voltar', doadores_path %>|
<%= link_to 'Pagina inicial', root_path %> 

app/views/doados/_form.html.erb
<%= form_with(model: doado, local: true) do |form| %>
  <% if doado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doado.errors.count, "error") %> prohibited this doado from being saved:</h2>

      <ul>
      <% doado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="field">
    <%= form.label :doador_id %>
    <%= collection_select(:doado , :doador_id , Doador.all , :id , :CPF , prompt: true) %>
  </div>


  <div class="field">
    <%= form.label :Data %>
    <%= form.date_select :Data %>
  </div>

  <div class="field">
    <%= form.label "mls" %>
    <%= form.text_field :Litros %>
  </div>

  <div class="field">
    <%= form.label :Local %>
  <%= select("doado","Local",['Brasília/DF','São Paulo/SP'],{prompt: true})%>
  </div>

  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doados/edit.html.erb
<h1>Editando doação</h1>
<%if current_funcionario.gerente==true%>

<%= render 'form', doado: @doado %>
<%else%>
	<p>Apenas para Gerentes</p>
	<%end%>

<%= link_to 'Mostar atual', @doado %> |
<%= link_to 'Voltar', doados_path %>

app/views/doados/index.html.erb
<h1>Doações</h1>
<%=image_tag("logos/lista.png",size: "100x130", alt: "Edit Entry")%>
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      
      <th>Data</th>
      <th>mls</th>
      <th>Local</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doados.each do |doado| %>
      <tr>

        <td>
          <p><%= "#{doado.Data.day}-#{doado.Data.month}-#{doado.Data.year}" %></p>
          </td>
        <td><%= doado.Litros %></td>
        <td><%= doado.Local %></td>

        <td><%= link_to 'Mostrar', doado %></td>
          <%if current_funcionario.gerente==true%>
        <td><%= link_to 'Editar', edit_doado_path(doado) %></td>
        <td><%= link_to 'Apagar', doado, method: :delete, data: { confirm: 'Deseja apagar este registro?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Registrar nova doação', new_doado_path %>|<%= link_to 'Pagina inicial', root_path %> 

app/views/doados/new.html.erb
<h1>Nova doação</h1>
<%=image_tag("logos/registros.png",size: "100x130", alt: "Edit Entry")%>
<%= render 'form', doado: @doado %>

<%= link_to 'voltar', doados_path %>

app/views/doados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doador:</strong>
  <%= @doado.doador.Nome %>
</p>

<p>
  <strong>Data:</strong>

</p>
 <%= @doado.Data.day %> 
            /
 <%= @doado.Data.month %>
            /
 <%= @doado.Data.year%>

<p>
  <strong>ml's doados:</strong>
  <%= @doado.Litros %>
</p>

<p>
  <strong>Local:</strong>
  <%= @doado.Local %>
</p>
<%if current_funcionario.gerente==true%>
<%= link_to 'Editar', edit_doado_path(@doado) %>
<%end%> |
<%= link_to 'voltar', doados_path %>

app/views/funcionarios/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/funcionarios/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Entrar como #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ep3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb

 <%=image_tag("logos/bemvindo.png")%>
 <p id="notice"><%= notice %></p>
 <br>


<p>
	
<ul> <%if !funcionario_signed_in?%>
	<li><%= link_to "Login", new_funcionario_session_url  %></li>
	<li><%= link_to "Cadastro de funcionarios", new_funcionario_registration_url  %></li>
	<%end%>
	
	<%if funcionario_signed_in?%>

     <%if current_funcionario.gerente==true%>
     <li>Gerente:<%= current_funcionario.email%></li>
     <li><%= link_to "Listagem de funcionarios", controller: "controll_funcionarios", action: "index" %></li>
     <%else%>
     <li>Funcionario:<%= current_funcionario.email%></li>
     <%end%>





	<li><%= link_to "sair", destroy_funcionario_session_path, method: :delete %></li>
	<%end%>
</ul>	
</p>

<p>
 <ul>
 	<li><%= link_to "Doadores", controller: "doadores", action: "index" %></li>
    <li><%= link_to "Doações", controller: "doados", action: "index" %></li>
 </ul> 

</p>